network:
  name: "Corporate_Network"
  devices:
    - id: "device01"
      type: "router"
      ip: "192.168.0.1"
      status: "active"
    - id: "device02"
      type: "switch"
      ip: "192.168.0.2"
      status: "active"
    - id: "device03"
      type: "server"
      ip: "192.168.0.3"
      status: "offline"
firewall:
  status: "enabled"
  rules:
    - allow: "192.168.0.10"
    - block: "10.0.0.0/8"
