network:
  name: "Corporate_Network"
  devices:
    - id: "device00"
      type: "server"
      ip: "22001:0db8:85a3:0000:0000:8a2e:0370:7334:80"
      status: "online"
    - id: "device01"
      type: "router"
      ip: "192.168.0.1"
      status: "active"
    - id: "device02"
      type: "switch"
      ip: "192.168.0.2"
      status: "active"
    - id: "device03"
      type: "server"
      ip: "192.168.0.3"
      status: "offline"
    - id: "device04"
      type: "server"
      ip: "192.168.0.4:80"
      status: "online"
    - id: "device05"
      type: "server"
      ip: "2001:0db8:85a3:0000:0000:8a2e:0370:7334"
      status: "online"
    - id: "device06"
      type: "server"
      ip: "2001:db8:85a3::8a2e:370:7334"
      status: "online"
firewall:
  status: "enabled"
  rules:
    - allow: "192.168.0.10"
    - block: "10.0.0.0/8"
